import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'

const navigationConfig = [
    {
        key: 'home',
        path: '/home',
        title: 'Dashboard',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'manage-group',
        title: 'Manage',
        translateKey: 'nav.manage',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'gear',
                path: '/gear',
                title: 'Gear',
                translateKey: 'nav.gear',
                icon: 'gear',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'food',
                path: '/food',
                title: 'Food',
                translateKey: 'nav.food',
                icon: 'food',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'categories',
                path: '/categories',
                title: 'Categories',
                translateKey: 'nav.categories',
                icon: 'categories',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'plan-group',
        title: 'Plan',
        translateKey: 'nav.plan',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'trips',
                path: '/trips',
                title: 'Trips',
                translateKey: 'nav.trips',
                icon: 'trips',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'conversations',
                path: '/conversations',
                title: 'Ask Carlo',
                translateKey: 'nav.conversations',
                icon: 'carlo',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'import',
        path: '/import',
        title: 'Import from Lighterpack',
        translateKey: 'nav.import',
        icon: 'import',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
]

export default navigationConfig
